#!/bin/bash


# https://en.wikipedia.org/wiki/ANSI_escape_code#Colors
COLOR16=(
    'Black'   '\033[30m'
    'Red'     '\033[31m'
    'Green'   '\033[32m'
    'Yellow'  '\033[33m'
    'Blue'    '\033[34m'
    'Magenta' '\033[35m'
    'Cyan'    '\033[36m'
    'White'   '\033[37m'

    'Bright Black (Gray)'  '\033[90m'
    'Bright Red'           '\033[91m'
    'Bright Green'         '\033[92m'
    'Bright Yellow'        '\033[93m'
    'Bright Blue'          '\033[94m'
    'Bright Magenta'       '\033[95m'
    'Bright Cyan'          '\033[96m'
    'Bright White'         '\033[97m'
)


echo "=========================================="
echo "    ANSI Standard Colors 16 (3 & 4 bit)   "
echo "=========================================="
echo


for ((i=0; i<${#COLOR16[@]}; i+=2)); do
    printf "%2s - ${COLOR16[i+1]}${COLOR16[i]}\033[0m\n" "$((i / 2))"
done


echo
echo "=========================================="
echo "             Test Complete                "
echo "=========================================="
