#!/bin/bash


## Imports


set -o errexit # exit on non-zero exit code

COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Colored Text


gum style --border normal --margin "1 0" --padding "1 0" \
          --width 30 --align="center" \
          --border-foreground 236 \
          --foreground $GUM_PINK ":: Gum Colors ::"

gum style --foreground $GUM_BLUE " -> Some colored text <-"
gum style --foreground $GUM_CYAN " -> Some colored text <-"
gum style --foreground $GUM_GREEN " -> Some colored text <-"
gum style --foreground $GUM_YELLOW " -> Some colored text <-"
gum style --foreground $GUM_RED " -> Some colored text <-"
gum style --foreground $GUM_PINK " -> Some colored text <-"
gum style --foreground $GUM_WHITE " -> Some colored text <-"
echo
