#!/bin/bash


## Imports


set -o errexit # exit on non-zero exit code

COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Tests


# Test function
print_color() {
    printf "${1}%-20s${STYLE_CLR} %s\n" "$2" "$3"
}

echo "=========================================="
echo "  ANSI Color and Style Test"
echo "=========================================="
echo

echo "--- Text Styles ---"
print_color "${STYLE_BOLD}" "STYLE_BOLD" "Bold text"
print_color "${STYLE_DIM}" "STYLE_DIM" "Dimmed text"
print_color "${STYLE_ITALIC}" "STYLE_ITALIC" "Italic text"
print_color "${STYLE_UNDERLINE}" "UNDERLINE" "Underlined text"
print_color "${STYLE_BLINK}" "BLINK" "Blinking text"
print_color "${STYLE_REVERSE}" "STYLE_REVERSE" "Reversed colors"
print_color "${STYLE_HIDDEN}" "HIDDEN" "Hidden text (you shouldn't see this)"
echo

echo "--- Standard Foreground Colors ---"
print_color "${FG_BLACK}" "BLACK" "Black text"
print_color "${FG_RED}" "RED" "Red text"
print_color "${FG_GREEN}" "GREEN" "Green text"
print_color "${FG_YELLOW}" "FG_YELLOW" "Yellow text"
print_color "${FG_BLUE}" "BLUE" "Blue text"
print_color "${FG_MAGENTA}" "MAGENTA" "Magenta text"
print_color "${FG_CYAN}" "CYAN" "Cyan text"
print_color "${FG_WHITE}" "WHITE" "White text"
echo

echo "--- Standard Background Colors ---"
print_color "${BG_BLACK}" "BG_BLACK" "Black background"
print_color "${BG_RED}" "BG_RED" "Red background"
print_color "${BG_GREEN}" "BG_GREEN" "Green background"
print_color "${BG_YELLOW}" "BG_YELLOW" "Yellow background"
print_color "${BG_BLUE}" "BG_BLUE" "Blue background"
print_color "${BG_MAGENTA}" "BG_MAGENTA" "Magenta background"
print_color "${BG_CYAN}" "BG_CYAN" "Cyan background"
print_color "${BG_WHITE}" "BG_WHITE" "White background"
echo

echo "--- Combined Styles ---"
printf "${STYLE_BOLD}${FG_RED}Bold Red${STYLE_CLR}\n"
printf "${STYLE_UNDERLINE}${FG_BLUE}Underlined Blue${STYLE_CLR}\n"
printf "${STYLE_BOLD}${STYLE_ITALIC}${FG_GREEN}Bold Italic Green${STYLE_CLR}\n"
printf "${STYLE_REVERSE}${FG_YELLOW}Reversed Yellow${STYLE_CLR}\n"
printf "${BG_BLUE}${FG_YELLOW}Yellow on Blue${STYLE_CLR}\n"
printf "${STYLE_BOLD}${BG_MAGENTA}${FG_WHITE}Bold White on Magenta${STYLE_CLR}\n"
printf "${STYLE_BOLD}${STYLE_DIM}${FG_BLUE}Bold dim blue${STYLE_CLR}\n"
echo

echo "=========================================="
echo "  Test Complete"
echo "=========================================="
