#!/bin/bash


# https://en.wikipedia.org/wiki/ANSI_escape_code#8-bit

print_color256() {
    local color_style="\033[38;5;${1}m"
    printf "| %b%03d%b " $color_style $1 '\033[0m'
}


echo "=========================================="
echo "    ANSI Standard Colors 256 (8 bit)      "
echo "=========================================="
echo

row_size=0
for ((i=16; i<256; i++)); do
    print_color256 $i
    ((row_size += 1))
    if ((row_size == 12)); then
        row_size=0
        printf "|\n"
    fi
done


echo
echo "=========================================="
echo "             Test Complete                "
echo "=========================================="
