#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code

# COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
# source <(echo "$COMMON")
source common

set +o errexit # disable exit on non-zero exit code


## Routines


# shellcheck disable=SC2329
enable_colors_pacman() {
    if $(check_sudo) grep -q '^Color$' "/etc/pacman.conf"; then
        # Enabled already
        return 0
    fi

    if $(check_sudo) grep -q '^#Color$' "/etc/pacman.conf"; then
        # Uncomment line "Color" in the config
        if replace_line /etc/pacman.conf "^#Color$" "Color" "$(check_sudo)"; then
            return 0
        fi
    fi

    return 2 # fail
}


main() {

    ## Get gum

    request_gum
    assert $? "no gum - no fun :("

    ## Logging

    printf_section "Logging\n"
    start_logger
    printf_action "Log started: ${STYLE_CLR}${LOG_FILE}\n"

    ## Pacman

    printf_section "Configuring Pacman\n"

    # Enable colors
    export -f enable_colors_pacman
    action_request_permission "to modify pacman.conf"
    action_run "Enabling pacman colors" "enable_colors_pacman" "done"

    ## Reflector

    printf_section "Installing Reflector\n"

    # Reflector package
    action_require_package "reflector"

    # Configure mirror sorting [reflector.conf]
    action_request_permission "to update reflector.conf"
    action_run "Configure mirror sorting to 'rate'" \
        "replace_line /etc/xdg/reflector/reflector.conf '^--sort age' '--sort rate' '$(check_sudo)'" \
        "done"

    # Set mirror update only on AC [reflector.service]
    # TODO: add config_set_param function
    if ! grep -q -E '^\s*ConditionACPower' "/usr/lib/systemd/system/reflector.service"; then
        # ConditionACPower is not set in .service yet
        action_request_permission "to update reflector.service"
        action_run "Configure reflector to run on AC only" \
            "$(check_sudo) sed -i '/^\[Unit\]/aConditionACPower=true' /usr/lib/systemd/system/reflector.service &>> ${LOG_FILE}" \
            "done"
    fi

    # Reload reflector config
    action_request_permission "to reflector daemon reload"
    action_run "Reload reflector daemon" "$(check_sudo) systemctl daemon-reload &>> ${LOG_FILE}" "done"

    # Enable reflector timer
    action_request_permission "to run reflector timer"
    action_run "Enable reflector timer" "$(check_sudo) systemctl enable reflector.timer &>> ${LOG_FILE}" "done"

    # Exclude mirrorlist from pacman package updates
    action_request_permission "to exclude mirrorlist from pacman updates"
    action_run "Exclude mirrorlist from pacman update" \
        "$(check_sudo) sed -i '/^\[options\]/aNoExtract = etc/pacman.d/mirrorlist' /etc/pacman.conf &>> ${LOG_FILE}" \
        "done"

    echo
    return 0
}


# Run main and return its exit code
main "$@"
exit $?
