#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code

COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Routines


main() {

    ## Get gum

    request_gum
    assert $? 'no gum - no fun :('

    ## Logging

    printf_section "Logging\n"
    start_logger
    printf_action "Log started: ${STYLE_CLR}${LOG_FILE}\n"

    ## Pacman

    printf_section "Configuring Pacman\n"

    # Enable colors
    action_request_permission 'to modify pacman.conf'
    action_run 'Enabling pacman colors' \
        "config_set_param '/etc/pacman.conf' '^Color$' 'options' $(check_sudo)" \
        'done'

    ## Reflector

    printf_section "Installing Reflector\n"

    # Reflector package
    action_require_package 'reflector'

    # Configure mirror sorting [reflector.conf]
    action_request_permission 'to modify reflector.conf'
    action_run "Configure mirror sorting to 'rate'" \
        "replace_line /etc/xdg/reflector/reflector.conf '^--sort age' '--sort rate' '$(check_sudo)'" \
        'done'

    action_request_permission 'to modify reflector.service'
    action_run 'Configure reflector to run on AC only' \
        "config_set_param '/usr/lib/systemd/system/reflector.service'   \
                          '\s*ConditionACPower\s*=\s*true' 'Unit' $(check_sudo)" \
        'done'

    # Reload reflector config
    action_request_permission 'to reload reflector daemon'
    action_run 'Reload reflector daemon' \
        "$(check_sudo) systemctl daemon-reload" \
        'done'

    # Enable reflector timer
    action_request_permission 'to enable reflector timer'
    action_run 'Enable reflector timer' \
        "$(check_sudo) systemctl enable reflector.timer" \
        'done'

    # Exclude mirrorlist from pacman package updates
    action_request_permission 'to exclude mirrorlist from pacman updates'
    action_run 'Exclude mirrorlist from pacman update' \
        "config_set_param '/etc/pacman.conf'  \
                          '\s*NoExtract\s*=\s*etc/pacman.d/mirrorlist' \
                          'options' $(check_sudo)" \
        'done'

    echo
    return 0
}


# Run main and return its exit code
main "$@"
exit $?
