#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code

COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Runtime


# shellcheck disable=SC2329
fish_configure_highlighting() {
    # ANSI color codes:
    # https://hexdocs.pm/color_palette/ansi_color_codes.html

    # All 'set -U' calls are batched into a single fish invocation to avoid
    # spawning a separate fish process per variable.
    fish -c '
        # Hide fish greeting
        set -U fish_greeting ""

        # Set the emoji width (iTerm only?)
        set -U fish_emoji_width 2

        # Syntax highlighting
        # https://fishshell.com/docs/current/interactive.html#syntax-highlighting-variables
        set -U fish_color_normal AAA
        set -U fish_color_command blue --bold
        set -U fish_color_operator 0FB              # ( ), { }, ... # brwhite --bold ?
        set -U fish_color_param normal              # Disable highlighting
        set -U fish_color_autosuggestion 444
        set -U fish_color_comment 464 --italic
        set -U fish_color_quote BE7                 # "Text"
        set -U fish_color_escape 9EC                # "...\n"
        set -U fish_color_valid_path --underline
        set -U fish_color_error D55
        set -U fish_color_end FD6                   # Separators like ; and &
        set -U fish_color_redirection FD6           # Like >/dev/null
        set -U fish_color_history_current --bold
        set -U fish_color_search_match normal       # Disable highlighting

        # Pager
        # https://fishshell.com/docs/current/interactive.html#pager-color-variables
        set -U fish_pager_color_prefix brwhite --bold
        set -U fish_pager_color_selected_prefix black
        set -U fish_pager_color_completion normal
        set -U fish_pager_color_selected_completion black
        set -U fish_pager_color_description 555
        set -U fish_pager_color_selected_description black
        set -U fish_pager_color_selected_background --background=AFA
        set -U fish_pager_color_progress black --background=7FF
    '
}


# shellcheck disable=SC2329
fish_enable_starship() {
    # Ensure fish functions directory exists
    mkdir -p ~/.config/fish/functions
    assert $? 'failed to create fish functions directory'

    # Install starship config selector (autoloaded by fish)
    action_install_file ~/.config/fish/functions/select_starship_config.fish \
        "https://dimk90.github.io/anarchy/starship/select_starship_config.fish"

    # Remove old starship init to guarantee select_starship_config call before init
    remove_line ~/.config/fish/config.fish 'starship init fish \| source'
    assert $? 'failed to remove old starship init'

    # Add starship init with config selector
    config_set_param ~/.config/fish/config.fish \
        'select_starship_config; starship init fish \| source'
    assert $? 'failed to add starship init with config selector'
}


# shellcheck disable=SC2329
bash_enable_starship() {
    # Download starship config selector function
    action_install_file ~/.config/starship/select_starship_config.bash \
        "https://dimk90.github.io/anarchy/starship/select_starship_config.bash"

    # Remove old starship init to guarantee select_starship_config call before init
    remove_line ~/.bashrc 'starship init bash'
    assert $? 'failed to remove old starship init'

    # Drop any previous inline selector definition from .bashrc (multi-line block)
    sed -i '/^select_starship_config() {$/,/^}$/d' ~/.bashrc &>> "$LOG_FILE"
    assert $? 'failed to remove old starship config selector'

    # Source config selector
    config_set_param ~/.bashrc \
        'source ~/.config/starship/select_starship_config.bash'
    assert $? 'failed to add starship config selector source'

    # Add starship init with config selector
    config_set_param ~/.bashrc \
        'select_starship_config && eval "\$\(starship init bash\)"'
    assert $? 'failed to add starship init with config selector'
}


main() {

    ## Get gum

    request_gum
    assert $? 'no gum - no fun :('

    ## Init

    printf_section "Starting\n"
    printf_action "Common lib version: ${STYLE_CLR}${COMMON_VERSION}\n"
    start_logger
    printf_action "Log started: ${STYLE_CLR}${LOG_FILE}\n"

    ## Starship

    printf_section "Starship\n"
    action_require_package 'starship'
    assert $? 'failed to install starship'

    # Create starship dir for configs
    mkdir -p ~/.config/starship
    assert $? 'failed to create starship config directory'

    # Download fallback theme
    printf_action "Fallback theme: ${STYLE_CLR}pure-text\n"
    action_install_file ~/.config/starship/fallback.toml \
        "https://dimk90.github.io/anarchy/starship/starship.pure-text.toml"

    # Select & download starship theme
    local header
    header=$(prefix_printf "$(bullet_action)" 'Select starship theme (default: pure):\n')

    local choice
    choice=$(gum choose --cursor="      > "  \
                        --header="${header}" \
                        --limit=1            \
                        'pure' 'capsule' 'pure-text') || choice='pure'
    printf_action "Starship theme: ${STYLE_CLR}${choice}\n"
    action_install_file ~/.config/starship/starship.toml \
        "https://dimk90.github.io/anarchy/starship/starship.${choice}.toml"

    ## Fish

    if is_command_available 'fish'; then
        printf_section "Configure fish\n"

        export -f fish_configure_highlighting
        action_run 'Configure syntax highlighting' 'fish_configure_highlighting' 'done'

        export -f fish_enable_starship
        action_run 'Enable starship' 'fish_enable_starship' 'done'
    fi

    ## Bash

    if is_command_available 'bash'; then
        printf_section "Configure bash\n"

        export -f bash_enable_starship
        action_run 'Enable starship' 'bash_enable_starship' 'done'
    fi

    return 0
}


# Run main and return its exit code
main "$@"
