#!/bin/bash


# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code

COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Routines


install_font() {
    #
    # Install and set console font: spleen (default) or terminus
    #
    printf_section "Installing font\n"

    ## Select font

    local header
    header=$(prefix_printf "$(bullet_action)" 'Select console font (default: spleen):\n')

    local choice
    choice=$(gum choose --cursor="      > " \
                        --header="${header}" \
                        --limit=1            \
                        'spleen' 'terminus') || choice='spleen'
    printf_action "Console font: ${STYLE_CLR}${choice}\n"

    ## Install selected font

    local font_name
    if [ "$choice" = 'terminus' ]; then
        action_require_package 'terminus-font'
        font_name='ter-128b'
    else
        # spleen ships as a bundled PSF; kbd provides the consolefonts dir + setfont
        action_require_package 'kbd'
        action_request_permission 'to install spleen-16x32.psfu'
        action_install_file '/usr/share/kbd/consolefonts/spleen-16x32.psfu' \
                            'https://dimk90.github.io/anarchy/font/psf/spleen-16x32.psfu' \
                            "$(check_sudo)"
        font_name='spleen-16x32'
    fi

    ## Update /etc/vconsole.conf

    # Add new font setting
    local cmd_set_font
    cmd_set_font=$(printf '%b && %b' \
        "remove_line '/etc/vconsole.conf' '^FONT=' $(check_sudo)" \
        "echo 'FONT=${font_name}' | as_root tee -a /etc/vconsole.conf")
    action_request_permission 'for updating /etc/vconsole.conf'
    action_run 'Update font in /etc/vconsole.conf' \
        "${cmd_set_font}" \
        'done'
    assert $? "can't modify /etc/vconsole.conf"

    ## Update initramfs to include new font

    if is_command_available 'mkinitcpio'; then
        printf_action "%b ${STYLE_DIM}run${STYLE_CLR} %b ${STYLE_DIM}manually to embed the font in the system image${STYLE_CLR}\n" \
            "$(bullet_info)" \
            "$(gum style --foreground "$GUM_YELLOW" 'mkinitcpio -P')"
    fi

    ## Change current font

    action_run 'Change current font' "setfont ${font_name}" 'done'
}


install_mouse() {
    #
    # Install gpm for console mouse support: left-drag to select, middle-click
    # to paste. Provides copy/paste across the vconsole (shell <-> micro) where
    # there is no X11/Wayland clipboard.
    #
    printf_section "Installing mouse support\n"

    ## Install gpm

    action_require_package 'gpm'

    ## Enable gpm service

    action_request_permission 'to enable gpm'
    action_run 'Enable gpm.service'                   \
        'as_root systemctl enable --now gpm.service'  \
        'enabled'
    assert $? "can't enable gpm.service"
}


set_keymap() {
    remove_line '/etc/vconsole.conf' '^KEYMAP=' "$(check_sudo)" || return 1
    echo 'KEYMAP=us-extra' | as_root tee -a /etc/vconsole.conf
}


install_keymap() {
    #
    # Install and set custom keymap for console
    #
    printf_section "Installing keymap\n"

    ## Install kbd

    action_require_package 'kbd'

    ## Download & install keymap file

    action_request_permission 'to install us-extra.map'
    action_install_file '/usr/share/kbd/keymaps/i386/qwerty/us-extra.map' \
                        'https://dimk90.github.io/anarchy/vconsole/us-extra.map' \
                        "$(check_sudo)"

    ## Load keymap

    action_run 'Switch keymap: us-extra' 'loadkeys us-extra' 'done'

    ## Update /etc/vconsole.conf

    action_request_permission 'for updating /etc/vconsole.conf'
    export -f set_keymap
    action_run 'Update keymap in /etc/vconsole.conf' 'set_keymap' 'done'
    assert $? "can't modify /etc/vconsole.conf"
}


install_locale() {
    #
    # Set console locale to en_US.UTF-8
    #
    printf_section "Configuring locale\n"

    ## Uncomment en_US.UTF-8 in /etc/locale.gen

    # Backup /etc/locale.gen if it exists
    if [ -f '/etc/locale.gen' ]; then
        action_request_permission 'for backing up /etc/locale.gen'
        local backup_name
        backup_name=$(backup_file '/etc/locale.gen' "$(check_sudo)")
        assert $? "can't backup /etc/locale.gen"
        action_run "Backup created: ${STYLE_CLR}${backup_name}"
    fi

    # Enable en_US.UTF-8 in /etc/locale.gen
    action_request_permission 'for modifying /etc/locale.gen'
    action_run "$(printf "%b %b %b"   \
                         "$(gum style --faint 'Enable')" \
                         "$(gum style --foreground $GUM_YELLOW 'en_US.UTF-8')" \
                         "$(gum style --faint 'in /etc/locale.gen')${STYLE_DIM}")" \
        "replace_line /etc/locale.gen '^#en_US.UTF-8 UTF-8' 'en_US.UTF-8 UTF-8' $(check_sudo)"  \
        'done'
    assert $? "can't modify /etc/locale.gen"

    ## Generate locale

    action_request_permission 'for generating locale'
    action_run 'Regenerate locale' "$(check_sudo) locale-gen" 'done'
    assert $? "can't generate locale"

    ## Set locale in /etc/locale.conf

    # Backup /etc/locale.conf if it exists
    if [ -f '/etc/locale.conf' ]; then
        action_request_permission 'for backing up /etc/locale.conf'
        local backup_name
        backup_name=$(backup_file '/etc/locale.conf' "$(check_sudo)")
        assert $? "can't backup /etc/locale.conf"
        action_run "Backup created: ${STYLE_CLR}${backup_name}"
    fi

    # Update /etc/locale.conf
    local cmd_update_locale
    cmd_update_locale=$(printf '%b && %b' \
        "remove_line '/etc/locale.conf' '^LANG=' $(check_sudo)" \
        "echo 'LANG=en_US.UTF-8' | as_root tee -a /etc/locale.conf")
    action_request_permission 'for modifying /etc/locale.conf'
    action_run 'Updating locale.conf' "${cmd_update_locale}" 'done'
    assert $? "can't modify /etc/locale.conf"
}


main() {

    ## Get gum

    request_gum
    assert $? 'no gum - no fun :('

    ## Init

    printf_section "Starting\n"
    printf_action "Common lib version: ${STYLE_CLR}${COMMON_VERSION}\n"
    start_logger
    printf_action "Log started: ${STYLE_CLR}${LOG_FILE}\n"

    ## Ask user for items to install

    local section
    section=$(prefix_printf "$(bullet_section)" 'Confirm Items')

    local choices
    if choices=$(gum choose --no-limit --selected='*' --cursor="   > "  \
                     --header "${section}"                              \
                     'Locale - Set console locale to en_US.UTF-8'       \
                     'Keymap - US/ANSI keyboard with extra bindings for CTRL,SHIFT,ALT' \
                     'Font - HiDPI modern font for native terminal'   \
                     'Mouse - GPM daemon for console copy/paste (select + middle-click)'); then
        choices=${choices,,} # convert to lowercase for easier matching
    else
        return 0
    fi

    printf "%s\n" "$section"

    # Print number of selected items
    local num_choice
    num_choice=$([ -n "$choices" ] && wc -l <<< "$choices" || echo 0)
    printf_action "Selected items: ${STYLE_CLR}${num_choice}\n"

    # Empty choice means nothing to do -> exit
    if [ "$num_choice" -eq 0 ]; then
        echo
        return 0
    fi

    ## Create backup of /etc/vconsole.conf if needed

    if grep -q -e 'font' -e 'keymap' <<< "$choices"; then
        if [ -f '/etc/vconsole.conf' ]; then
            printf_section "Backup\n"
            action_request_permission 'for backing up /etc/vconsole.conf'
            local backup_name
            backup_name=$(backup_file '/etc/vconsole.conf' "$(check_sudo)")
            assert $? "can't backup /etc/vconsole.conf"
            action_run "$backup_name"
        fi
    fi

    ## Install selected items

    grep -q 'locale' <<< "$choices" && install_locale
    grep -q 'keymap' <<< "$choices" && install_keymap
    grep -q 'font'   <<< "$choices" && install_font
    grep -q 'mouse'  <<< "$choices" && install_mouse

    return 0
}


main "$@"
