#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code

COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Routines


print_result() {
    if [ "$1" -eq 0 ]; then
        printf " - %b\n" "$(gum style --bold --foreground $GUM_GREEN 'done')"
    else
        printf " - %b\n" "$(gum style --bold --foreground $GUM_RED 'failed')"
    fi
}


enable_colors_pacman() {
    if $(check_sudo) grep '^Color$' "/etc/pacman.conf" &> /dev/null; then
        return 0 # enabled already
    fi

    if $(check_sudo) grep '^#Color$' "/etc/pacman.conf" &> /dev/null; then
        # uncomment line in the config
        $(check_sudo) sed -i 's/#Color/Color/' /etc/pacman.conf &>> "$LOG_FILE"
        return $?
    fi

    return 1
}


main() {

    ## Get gum

    request_gum
    assert $? "no gum - no fun :("

    ## Enable colors

    printf_section "Enabling Colors\n"

    # pacman
    action_request_permission "for pacman.conf access"
    printf_action "pacman colors"
    enable_colors_pacman
    print_result $?

    return 0
}


# Run main and return its exit code
main "$@"
exit $?
