#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code

COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Routines


print_result() {
    case $1 in
        0) printf " - %b\n" "$(gum style --bold --foreground $GUM_GREEN 'done')"
           ;;
        1) printf " - %b\n" "$(gum style --bold --foreground $GUM_GREEN 'enabled')"
           ;;
        *) printf " - %b\n" "$(gum style --bold --foreground $GUM_RED 'failed')"
           ;;
    esac
}


enable_colors_pacman() {
    if $(check_sudo) grep -q '^Color$' "/etc/pacman.conf"; then
        # Enabled already
        return 1
    fi

    if $(check_sudo) grep -q '^#Color$' "/etc/pacman.conf"; then
        # Uncomment line "Color" in the config
        if replace_line /etc/pacman.conf "^#Color$" "Color" "$(check_sudo)"; then
            return 0
        fi
    fi

    return 2 # fail
}


main() {

    ## Get gum

    request_gum
    assert $? "no gum - no fun :("

    ## Logging

    printf_section "Logging\n"
    start_logger
    printf_action "Log started: ${CLR}${LOG_FILE}\n"

    ## Enable colors

    printf_section "Enabling Colors\n"

    # pacman
    action_request_permission "for pacman.conf access"
    printf_action "pacman colors"
    enable_colors_pacman
    print_result $?


    echo
    return 0
}


# Run main and return its exit code
main "$@"
exit $?
