#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code
COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Runtime

#
# TODO:
#
# [x] zoxide
#     [ ] test `ji`  / fzf
#     [ ] plugin for file manager
# [x] less
#     [x] default pager
# [x] bat -> cat
#     [ ] less colorization
#     [ ] colorized help
#     [x] colorized man
#     [x] cat alias
#     [x] theme
# [ ] fzf
#    - theme
#    - remove keybindings ??
#           fish -c "set -U FZF_LEGACY_KEYBINDINGS 1"
#    - configure with bat
# [ ] better man
# [ ] ripgrep -> grep
# [ ] delta -> diff
# [ ] fd -> find
# [ ] file manager
#


# shellcheck disable=SC2329
bash_enable_zoxide() {
    config_set_param ~/.bashrc 'eval "\$\(zoxide init --cmd j bash\)"'
}

# shellcheck disable=SC2329
fish_enable_zoxide() {
    config_set_param ~/.config/fish/config.fish 'zoxide init --cmd j fish \| source'
}

# shellcheck disable=SC2329
fish_add_help_colorization() {
    config_set_param ~/.config/fish/config.fish \
        "abbr -a --position anywhere -- --help '--help \| bat -plhelp --theme TwoDark'"

    # Note: some command use -h not for help, e.g. ls -h
    # abbr -a --position anywhere -- -h '-h | bat -plhelp --theme TwoDark'
}


install_zoxide() {
    printf_section "zoxide\n"

    # Install if missing
    action_require_package 'zoxide'

    # Enable for fish and bash
    export -f bash_enable_zoxide
    action_run 'Enable zoxide for bash' 'bash_enable_zoxide' 'done'

    if is_command_available 'fish'; then
        export -f fish_enable_zoxide
        action_run 'Enable zoxide for fish' 'fish_enable_zoxide' 'done'
    fi

    # Add alias for cd

    # shellcheck disable=SC2155
    local shells=$(alias_set_permanent 'cd' 'j')
    action_run 'Set alias cd->zoxide' '' "${shells}"
}


install_less() {
    printf_section "less\n"

    # Install if missing
    action_require_package 'less'

    # Set as default pager
    shells=$(env_set_permanent 'PAGER' 'less')
    action_run 'Set less as default pager' '' "${shells}"
}


install_bat() {
    printf_section "bat\n"

    # Install if missing
    action_require_package 'bat'

    # Install config
    mkdir -p ~/.config/bat
    assert $? 'Failed to create config directory for bat'
    action_install_file ~/.config/bat/config \
        'https://dimk90.github.io/anarchy/cli/bat.cfg'

    # Set alias for cat
    local shells
    shells=$(alias_set_permanent 'cat' 'bat')
    action_run 'Set alias cat->bat' '' "${shells}"

    # Use bat for man colorization
    shells=$(env_set_permanent 'MANPAGER' 'bat -plman --theme TwoDark')
    action_run 'Register bat for man colorization' '' "${shells}"

    # Add --help colorization
    if is_command_available 'fish'; then
        export -f fish_add_help_colorization
        action_run 'Add --help colorization (fish only)' \
            'fish_add_help_colorization' 'done'
    fi
}


main() {

    ## Get gum

    request_gum
    assert $? 'no gum - no fun :('

    ## Init

    printf_section "Starting\n"
    printf_action "Common lib version: ${STYLE_CLR}${COMMON_VERSION}\n"
    start_logger
    printf_action "Log started: ${STYLE_CLR}${LOG_FILE}\n"

    ## Install CLI

    install_zoxide
    install_less
    install_bat

    return 0
}


main "$@"
exit $?
