#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code
COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Runtime

#
# TODO:
#
# [x] zoxide
#     [ ] test `ji`  / fzf
#     [ ] plugin for file manager
# [x] less
#     [x] default pager
# [ ] bat -> cat
#     [ ] BAT_PAGER ?
#     [ ] colorized help
#     [ ] colorized man
#     [ ] cat alias
#     [ ] theme
# [ ] better man
# [ ] fzf
#    - theme
#    - remove keybindings ??
#           fish -c "set -U FZF_LEGACY_KEYBINDINGS 1"
#    - configure with bat
# [ ] ripgrep -> grep
# [ ] delta -> diff
# [ ] fd -> find
# [ ] file manager
#


# shellcheck disable=SC2329
bash_enable_zoxide() {
    config_set_param ~/.bashrc 'eval "\$\(zoxide init --cmd j bash\)"'
}

# shellcheck disable=SC2329
fish_enable_zoxide() {
    config_set_param ~/.config/fish/config.fish 'zoxide init --cmd j fish \| source'
}


install_zoxide() {
    printf_section "zoxide\n"

    # Install if missing
    action_require_package 'zoxide'

    # Enable for fish and bash
    export -f bash_enable_zoxide
    action_run 'Enable zoxide for bash' 'bash_enable_zoxide' 'done'

    if is_command_available 'fish'; then
        export -f fish_enable_zoxide
        action_run 'Enable zoxide for fish' 'fish_enable_zoxide' 'done'
    fi

    # Add alias for cd

    # shellcheck disable=SC2155
    local result=$(alias_set_permanent 'cd' 'j')
    action_run 'Set alias cd->zoxide' '' "${result}"
}


install_less() {
    printf_section "less\n"
    # Install if missing
    action_require_package 'less'
    # Set as default pager
    shells=$(env_set_permanent 'PAGER' 'less')
    action_run 'Set less as default pager' '' "${shells}"
}


main() {

    ## Get gum

    request_gum
    assert $? 'no gum - no fun :('

    ## Init

    printf_section "Starting\n"
    printf_action "Common lib version: ${STYLE_CLR}${COMMON_VERSION}\n"
    start_logger
    printf_action "Log started: ${STYLE_CLR}${LOG_FILE}\n"

    ## Install CLI

    install_zoxide
    install_less


    return 0
}



main "$@"
exit $?
