#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code
COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Runtime

#
# TODO:
#
# [x] zoxide
#     [x] test `ji`  / fzf
#     [ ] plugin for file manager
#     [x] add cdi alias for ji
# [x] less
#     [x] default pager
#     [x] keep ANSI color in the input
# [x] bash-completion
# [x] bat -> cat
#     [x] colorized help
#     [x] colorized man
#     [x] cat alias
#     [x] theme
#     [ ] test colors in native linux terminal
# [x] fd
#     [ ] fix color theme
# [x] ripgrep -> grep
# [x] ls -> eza (or lsd)
#     [x] git support
#     [x] icons (bigger than default)
#     [x] colors / theme
#     [x] alias: ls, ll
#     [ ] test colors in native terminal
# [x] better man: tldr
# [ ] delta -> diff
#     [ ] git integration: https://github.com/dandavison/delta?tab=readme-ov-file#a-syntax-highlighting-pager-for-git-diff-and-grep-output
#     [ ] grep integration
#     [ ] color theme
#     [ ] test colors in native terminal
# [x] fzf
#     [x] default fzf setting: https://github.com/junegunn/fzf/blob/master/ADVANCED.md#color-themes
#     [x] custom color theme for fzf and fzf.fish
#     [x] fzf aliases:
#         [x] fzf-fd
#         [x] fzf-ps
#         [x] fzf-history
#         [x] fzf-env
#         [x] fzf-git-log
#         [x] fzf-git-status
#         [ ] fzf-grep: https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-between-ripgrep-mode-and-fzf-mode
#         [ ] fzf-pacman: https://wiki.archlinux.org/title/Fzf
#             [ ] abbr for -Q, -Ss, -R, ... ?
#     [x]
#     [x] faster search with fd
#           - search hidden files also
#           - follow symlink: https://github.com/junegunn/fzf?tab=readme-ov-file#respecting-gitignore
#     [x] fzf plugin for keybindings:
#           - Ctrl+Alt+F -> fd | fzf
#             [ ] include hidden files and folders
#           - Ctrl+Alt+L -> git log -> delta
#           - Ctrl+Alt+S -> git status -> delta
#           - Ctrl+Alt+P -> ps | fzf
#           - Ctrl+Alt+H -> history
#           - Ctrl+Alt+V -> env | fzf
#     [ ] update style to split screen without border, +bat borders: https://github.com/junegunn/fzf/blob/master/ADVANCED.md#switching-to-fzf-only-search-mode
#     [ ] test colors in native linux terminal
#
# [ ] file manager
#


# shellcheck disable=SC2329
bash_enable_zoxide() {
    config_set_param ~/.bashrc 'eval "\$\(zoxide init --cmd j bash\)"'
}

# shellcheck disable=SC2329
fish_enable_zoxide() {
    config_set_param ~/.config/fish/config.fish 'zoxide init --cmd j fish \| source'
}

# shellcheck disable=SC2329
fish_add_help_colorization() {
    config_set_param ~/.config/fish/config.fish \
        "abbr -a --position anywhere -- --help '--help \| bat -plhelp --theme TwoDark'"

    # Note: potential conflict with some commands
    #       which use -h not for help, e.g. ls -h
    config_set_param ~/.config/fish/config.fish \
        "abbr -a --position anywhere -- -h '-h \| bat -plhelp --theme TwoDark'"
}

# shellcheck disable=SC2329
fzf_configure_default() {
    # Run directory scan with fd by default
    env_set_permanent 'FZF_DEFAULT_COMMAND' \
        'fd --type f --color=always --hidden --follow --exclude .git'

    # Note: color theme playground: https://vitormv.github.io/fzf-themes/
    env_set_permanent 'FZF_DEFAULT_OPTS' \
        '--ansi --cycle --multi --layout=reverse --padding="0,1,0,1" --border --height=80% --prompt="Filter> " --marker="+ " --pointer="|" --info="right" --color=fg:-1,fg+:#d0d0d0,bg:-1,hl:#5f87af,hl+:#5fd7ff,info:#afaf87,marker:#60F090,prompt:#00F0B0,spinner:#87ff00,pointer:#60F090,header:#87afaf,border:#404040,label:#aeaeae,query:#d9d9d9'
}

fish_install_fzf_plugin() {
    local tmpdir
    tmpdir=$(mktemp -d) || return 1
    git clone https://github.com/PatrickF1/fzf.fish "$tmpdir" || { rm -rf "$tmpdir"; return 1; }
    rm -rf ~/.config/fish/plugins/fzf.fish
    mv "$tmpdir" ~/.config/fish/plugins/fzf.fish || return 1
    # Symlink the plugin files into fish config dirs
    ln -sf ~/.config/fish/plugins/fzf.fish/functions/*    ~/.config/fish/functions/   || return 1
    ln -sf ~/.config/fish/plugins/fzf.fish/conf.d/*       ~/.config/fish/conf.d/      || return 1
    ln -sf ~/.config/fish/plugins/fzf.fish/completions/*  ~/.config/fish/completions/ || return 1
    # Adjust some keybindings
    # Note: must be single call to fzf_configure_bindings
    config_set_param ~/.config/fish/config.fish 'fzf_configure_bindings --variables=ctrl-alt-v --history=ctrl-alt-h'
}

# shellcheck disable=SC2329
fzf_install_fish_aliases() {
    local FZF_ALIASES=(
        fzf-fd
        fzf-ps
        fzf-history
        fzf-env
        fzf-git-log
        fzf-git-status
    )

    mkdir -p ~/.config/fish/functions

    for alias in "${FZF_ALIASES[@]}"; do
        action_install_file "$HOME/.config/fish/functions/${alias}.fish" \
            "https://dimk90.github.io/anarchy/cli/${alias}.fish"
    done
}

# shellcheck disable=SC2329
fzf_install_bash_aliases() {
    mkdir -p ~/.config/bash
    action_install_file ~/.config/bash/fzf-aliases.bash \
        'https://dimk90.github.io/anarchy/cli/fzf-aliases.bash'
    config_set_param ~/.bashrc 'source ~/\.config/bash/fzf-aliases\.bash'
}


install_zoxide() {
    printf_section "zoxide\n"
    action_require_package 'zoxide'

    # Enable for fish and bash
    export -f bash_enable_zoxide
    action_run 'Enable zoxide for bash' 'bash_enable_zoxide' 'done'

    if is_command_available 'fish'; then
        export -f fish_enable_zoxide
        action_run 'Enable zoxide for fish' 'fish_enable_zoxide' 'done'
    fi

    # Add alias for cd

    # shellcheck disable=SC2155
    local shells=$(alias_set_permanent 'cd' 'j')
    action_run 'Set alias cd->zoxide' '' "${shells}"

    # shellcheck disable=SC2155
    shells=$(alias_set_permanent 'cdi' 'ji')
    action_run 'Set alias cdi->zoxide(interactive)' '' "${shells}"
}


install_less() {
    printf_section "less\n"
    action_require_package 'less'

    # Set as default pager
    local shells
    shells=$(env_set_permanent 'PAGER' 'less')
    action_run 'Set less as default pager' '' "${shells}"

    # Set default options
    shells=$(alias_set_permanent 'less' 'less -RFXi --mouse')
    action_run 'Set default options' '' "${shells}"
}


install_bash_completion() {
    printf_section "bash-completion\n"
    action_require_package 'bash-completion'
}


install_bat() {
    printf_section "bat\n"
    action_require_package 'bat'

    # Install config
    mkdir -p ~/.config/bat
    assert $? 'Failed to create config directory for bat'
    action_install_file ~/.config/bat/config \
        'https://dimk90.github.io/anarchy/cli/bat.cfg'

    # Set alias for cat
    local shells
    shells=$(alias_set_permanent 'cat' 'bat')
    action_run 'Set alias cat->bat' '' "${shells}"

    # Use bat for man colorization
    shells=$(env_set_permanent 'MANPAGER' 'bat -plman --theme TwoDark')
    action_run 'Register bat for man colorization' '' "${shells}"

    # Add --help colorization
    if is_command_available 'fish'; then
        export -f fish_add_help_colorization
        action_run 'Add --help colorization' 'fish_add_help_colorization' 'fish shell'
    fi
}


install_fd() {
    printf_section "fd\n"
    action_require_package 'fd' '' 'fd-find'
}


install_rg() {
    printf_section "ripgrep\n"
    action_require_package 'ripgrep'

    # Set alias for grep
    # shellcheck disable=SC2155
    local shells=$(alias_set_permanent 'grep' 'rg')
    action_run 'Set alias grep->rg' '' "${shells}"
}


install_eza() {
    printf_section "eza\n"
    action_require_package 'eza'

    # Install custom theme
    mkdir -p ~/.config/eza
    action_install_file ~/.config/eza/theme.yml \
        'https://dimk90.github.io/anarchy/cli/eza-theme.yml'

    # Configure alias for eza
    local shells
    # shellcheck disable=SC2034
    shells=$(alias_set_permanent 'ls' 'eza')
    action_run 'Set alias: ls' '' "${shells}"
    # shellcheck disable=SC2034
    shells=$(alias_set_permanent 'll' 'eza -lahF --icons --group-directories-first --git --header')
    action_run 'Set alias: ll' '' "${shells}"
    # shellcheck disable=SC2034
    shells=$(alias_set_permanent 'll-size' 'll --total-size')
    action_run 'Set alias: ll-size' '' "${shells}"
    # shellcheck disable=SC2034
    shells=$(alias_set_permanent 'lt' 'll --tree --level=2')
    action_run 'Set alias: lt' '' "${shells}"
    # shellcheck disable=SC2034
    shells=$(alias_set_permanent 'lt-size' 'lt --total-size')
    action_run 'Set alias: lt-size' '' "${shells}"
}


install_tldr() {
    printf_section "man & tldr\n"
    action_require_package 'man-db'
    action_require_package 'tldr'
}


install_fzf() {
    printf_section "fzf\n"
    action_require_package 'fzf'

    # Configure default command and options (fzf.fish style)
    export -f fzf_configure_default
    action_run 'Configure default options' 'fzf_configure_default' 'done'

    # Install fzf.fish plugin
    # Set fzf aliases
    if is_command_available 'fish'; then
        fzf_install_fish_aliases
    fi

    if is_command_available 'bash'; then
        fzf_install_bash_aliases
    fi
}


main() {

    ## Get gum

    request_gum
    assert $? 'no gum - no fun :('

    ## Init

    printf_section "Starting\n"
    printf_action "Common lib version: ${STYLE_CLR}${COMMON_VERSION}\n"
    start_logger
    printf_action "Log started: ${STYLE_CLR}${LOG_FILE}\n"

    ## Install CLI

    install_zoxide
    install_less
    install_bash_completion
    install_bat
    install_fd
    install_rg
    install_eza
    install_tldr
    install_fzf

    return 0
}


main "$@"
