#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code

COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Routines


main() {

    ## Refuse to run as root
    # makepkg cannot (and must not) be run as root; yay is for a real user.
    if [ "$EUID" -eq 0 ]; then
        printf_error "%b\n" 'this script must be run as a non-root user'
        exit 1
    fi

    ## Get gum

    request_gum
    assert $? 'no gum - no fun :('

    ## Init

    printf_section "Starting\n"
    printf_action "Common lib version: ${STYLE_CLR}${COMMON_VERSION}\n"
    start_logger
    printf_action "Log started: ${STYLE_CLR}${LOG_FILE}\n"

    ## Install

    printf_section "Installing & Configuring\n"

    # Install yay if missing
    if ! is_command_available yay; then
        # build deps: git for cloning, base-devel for makepkg
        action_require_package 'git'
        action_require_package 'base-devel'

        # Create unique temp dir for the PKGBUILD clone
        local tmpdir
        tmpdir=$(mktemp -d)
        assert $? "can't create temporary directory"
        # shellcheck disable=SC2064
        trap "rm -rf '$tmpdir'" EXIT

        # Clone yay's PKGBUILD
        action_run "Cloning yay's PKGBUILD" \
            "git clone https://aur.archlinux.org/yay.git $tmpdir" \
            'done'
        assert $? "failed to clone yay's PKGBUILD"

        # Build package
        action_run 'Building' \
            "makepkg -s --noconfirm -D $tmpdir" \
            'done'
        assert $? 'failed to build and install yay'

        # Install
        action_request_permission 'for installing yay'
        action_run 'Installing yay' \
            "sudo pacman -U --noconfirm $tmpdir/yay-*.pkg.tar.zst" \
            'done'
        assert $? 'failed to install yay'
    else
        printf_action 'yay is installed already\n'
    fi

    # Enable color in the pipe also: e.g. yay -Ss ... | less -R
    action_run 'Enabling color in the pipe' \
        "alias_set_permanent 'yay' 'yay --color=always'" \
        'done'

    return 0
}


main "$@"
