#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code

COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Routines


main() {

    ## Get gum

    request_gum
    assert $? "no gum - no fun :("

    ## Logging

    printf_section "Logging\n"
    start_logger
    printf_action "Log started: ${CLR}${LOG_FILE}\n"

    ## Install

    printf_section "Installing & Configuring\n"

    # git
    action_require_package "git"

    # Clone yay's PKGBUILD
    rm -rf "/tmp/anarchy-yay-install" &>> "${LOG_FILE}"
    action_run "Cloning yay's PKGBUILD" "git clone https://aur.archlinux.org/yay.git /tmp/anarchy-yay-install" "done"
    assert $? "failed to clone yay's PKGBUILD"

    # Build package
    action_run "Building" "makepkg -s --noconfirm -D /tmp/anarchy-yay-install" "done"
    assert $? "failed to build and install yay"

    # Install
    action_request_permission "for installing yay"
    action_run "Installing yay" "sudo pacman -U --noconfirm /tmp/anarchy-yay-install/yay-*.pkg.tar.zst" "done"
    assert $? "failed to install yay"

    echo
    return 0
}


# Run main and return its exit code
main "$@"
exit $?
