#!/bin/bash

# Treat unset variables as an error and exit immediately
set -o nounset


## Imports


set -o errexit # exit on non-zero exit code

COMMON=$(curl -fsSL "https://dimk90.github.io/anarchy/common")
# shellcheck source=common
source <(echo "$COMMON")

set +o errexit # disable exit on non-zero exit code


## Routines


main() {

    ## Get gum

    request_gum
    assert $? 'no gum - no fun :('

    ## Init

    printf_section "Starting\n"
    printf_action "Common lib version: ${STYLE_CLR}${COMMON_VERSION}\n"
    start_logger
    printf_action "Log started: ${STYLE_CLR}${LOG_FILE}\n"

    ## Ask user for items to install

    local section
    section=$(prefix_printf "$(bullet_section)" 'Confirm Items')

    local choices
    if ! choices=$(gum choose --no-limit --selected='*' \
                              --cursor="   > "          \
                              --header "${section}"     \
                              'Settings' 'Keybindings' 'Default Editor'); then
        return 0
    fi

    printf "%s\n" "$section"

    # Print number of selected items
    local num_choice
    num_choice=$([ -n "$choices" ] && wc -l <<< "$choices" || echo 0)
    printf_action "Selected items: ${STYLE_CLR}${num_choice}\n"

    # Empty choice means nothing to do -> exit
    if [ "$num_choice" -eq 0 ]; then
        echo
        return 0
    fi

    ## Install micro

    printf_section "Installing & Configuring\n"

    action_require_package 'micro'

    # Create micro config directory if it doesn't exist
    mkdir -p ~/.config/micro
    assert $? "can't create ~/.config/micro"

    ## Install selected items

    local shells

    # Install settings file
    if grep -q 'settings' <<< "${choices,,}"; then
        action_install_file "${HOME}/.config/micro/settings.json"  \
                            'https://dimk90.github.io/anarchy/micro/settings.json'

        # Replace obsolete MICRO_TRUECOLOR with truecolor=auto in settings (since micro 2.0.15)
        shells="$(env_unset_permanent 'MICRO_TRUECOLOR')"
        [ -n "$shells" ] && action_run "Remove MICRO_TRUECOLOR (in favor to settings) for ${STYLE_CLR}${STYLE_BOLD}$shells"
    fi

    # Install keybindings
    if grep -q 'settings' <<< "${choices,,}"; then
        action_install_file "${HOME}/.config/micro/bindings.json"  \
                            'https://dimk90.github.io/anarchy/micro/bindings.json'
    fi

    # Set as default editor
    if grep -q 'default editor' <<< "${choices,,}"; then
        shells="$(env_set_permanent 'EDITOR' 'micro')"
        [ -n "$shells" ] && action_run "Set EDITOR to micro for ${STYLE_CLR}${STYLE_BOLD}$shells"
    fi

    echo
    return 0
}


# Run main and return its exit code
main "$@"
exit $?
